message-kick: "You have been denied login by Firewall plugin."
list-block-netset-file:
- blocklist_de.ipset
- blocklist_net_ua.ipset
- firehol_abusers_1d.netset
- firehol_abusers_30d.netset
- firehol_anonymous.netset
- firehol_level1.netset
- firehol_level2.netset
- firehol_level3.netset
- firehol_proxies.netset
- vpn-ipv4.txt
list-unblock-uuid:
