name: Firewall
version: 1.0
api-version: 1.15
description: Firewall.
author: kubotan
main: space.gorogoro.firewall.Firewall

commands:
  firewall reload:
    description: Reload config.
    usage: /<command> reload
